export default {
  RESET_AUTH_STORE: "RESET_AUTH_STORE",

  SEND_REQUEST_CHECKVERSION: "SEND_REQUEST_CHECKVERSION",
  SEND_REQUEST_CHECKVERSION_SUCCESS: "SEND_REQUEST_CHECKVERSION_SUCCESS",
  SEND_REQUEST_CHECKVERSION_FAILURE: "SEND_REQUEST_CHECKVERSION_FAILURE",

};
